## Prompt Format
format = """
$directory\
$git_branch\
$git_status\
$memory_usage\
$cmd_duration\
$fill\
$c$java$lua$nodejs$ruby$rust\
$aws\
$line_break\
$character
"""

## Prompt-Wide Config
palette = 'dracula'
add_newline = false

## Modules Config
[directory]
disabled = false
format = '[$path]($style) '
style = 'bold cyan'
truncation_length = 10

[git_branch]
disabled = false
format = 'on [$symbol $branch ]($style)'
style = 'bold purple'
symbol = ''

[git_status]
disabled = false
format = '([\[$all_status$ahead_behind\] ]($style))'
style = 'bold orange'

conflicted = '!'
stashed = '$'
deleted = '-'
renamed = 'r'
modified = '~'
staged = '+'
untracked = '?'

diverged = '<>'
ahead = '>'
behind = '<'
up_to_date = '='

[cmd_duration]
disabled = false
format = 'took [$duration ]($style)'
style = 'bold yellow'
show_milliseconds = true

[fill]
disabled = false
symbol = ' '

[c]
disabled = false
format = '[$symbol $version ]($style)'
style = 'bold 149'
symbol = 'c'

[java]
disabled = false
format = '[$symbol $version ]($style)'
style = 'bold orange'
symbol = 'java'

[lua]
disabled = false
format = '[$symbol $version ]($style)'
style = 'bold blue'
symbol = 'lua'

[nodejs]
disabled = false
format = '[$symbol $version ]($style)'
style = 'bold green'
symbol = 'nodejs' 

[ruby]
disabled = false
format = '[$symbol $version ]($style)'
style = 'bold red'
symbol = 'rb'
detect_variables = []

[rust]
disabled = false
format = '[$symbol $version ]($style)'
style = 'bold red'
symbol = 'rs'

[aws]
disabled = false
format = '[$symbol ($profile::)($region )(\[$duration\] )]($style)'
style = 'bold pink'
symbol = '󰒋'

[line_break]
disabled = false

[character]
disabled = false
format = '$symbol '
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

## Palette Definitions
[palettes.dracula]
background = '#282a36'
current_line = '#44475a'
foreground = '#f8f8f2'
comment = '#6272a4'
cyan = '#8be9fd'
green = '#50fa7b'
orange = '#ffb86c'
pink = '#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'
