set -g status-bg "#282a36"

set -g @bg      "#282a36"
set -g @fg      "#f8f8f2"
set -g @line    "#44475a"
set -g @comment "#6272a4"
set -g @red     "#ff5555"
set -g @orange  "#ffb86c"
set -g @yellow  "#f1fa8c"
set -g @green   "#50fa7b"
set -g @blue    "#8be9fd"
set -g @purple  "#bd93f9"
set -g @pink    "#ff79c6"
