set -g status-bg "#2d353b"

set -g @bg      "#2d353b"
set -g @fg      "#d3c6aa"
set -g @line    "#343f44"
set -g @comment "#859289"
set -g @red     "#e67e80"
set -g @orange  "#e69875"
set -g @yellow  "#dbbc7f"
set -g @green   "#a7c080"
set -g @blue    "#7fbbb3"
set -g @purple  "#d699b6"
set -g @pink    "#83c092"
