set -g status-bg "#282828"

set -g @bg      "#282828"
set -g @fg      "#d4be98"
set -g @line    "#32302f"
set -g @comment "#928374"
set -g @red     "#ea6962"
set -g @orange  "#e78a4e"
set -g @yellow  "#d8a657"
set -g @green   "#a9b665"
set -g @blue    "#7daea3"
set -g @purple  "#d3869b"
set -g @pink    "#89b482"
