# Prompt Format ####
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character
"""

# Prompt-Wide Config ####
palette = 'dracula'
add_newline = false

# Modules Config ####
[directory]
disabled = false
format = '[$path]($style) '
style = 'bold cyan'
truncation_length = 10

[git_branch]
disabled = false
format = 'on [$symbol$branch]($style) '
style = 'bold purple'
symbol = ' '

[git_state]
disabled = false

[git_status]
disabled = false

[line_break]
disabled = false

[character]
disabled = false
format = '$symbol '
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

# Palette Definitions ####
[palettes.dracula]
background = '#282a36'
current_line = '#44475a'
foreground = '#f8f8f2'
comment = '#6272a4'
cyan = '#8be9fd'
green = '#50fa7b'
orange = '#ffb86c'
pink = '#ff79c6'
purple = '#bd93f9'
red = '#ff5555'
yellow = '#f1fa8c'

