## Reload Config
unbind r
bind r source-file ~/.config/tmux/.tmux.conf
display-message "RELOADED!"

# Re-bind leader
set -g prefix C-s

# Allow mouse
set -g mouse on

# Scrollback Buffer Size
set -g history-limit 50000

# Vim Controls
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins (Prefix-I to install plugins)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Dracula Plugin Settings
set -g @plugin 'dracula/tmux'

# Initialize TMUX plugin manager (keep this line at the very bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

