## Basic Tmux Controls
# tmux new -s [session-name]          : create a new session
# tmux kill-session -t [session-name] : delete a session
# tmux attach -t [session-name]       : attach to a session
# tmux detach                         : detach from the current session
# tmux ls                             : list all sessions

## Basic Tmux Shortcuts
# prefix + r           : reload tmux config
# prefix + I           : install plugins
# prefix + w           : session manager
# prefix + c           : create a window
# prefix + ,           : rename window
# prefix + [window-id] : switch to a specific window
# prefix + |           : split pane horizontally
# prefix + -           : split pane vertically
# prefix + h/j/k/l     : resize pane
# prefix + m           : maximize/minimize pane
# prefix + x           : kill pane
# prefix + !           : kill window
# prefix + c           : enter copy mode
# prefix + p           : paste

## Unbindings
unbind C-b
unbind %
unbind '"'
unbind !
unbind r
unbind s
unbind c
unbind p

## Global Settings
set-environment -g TMUX_PLUGIN_MANAGER_PATH ~/.tmux/plugins # change TPM plugin directory
set -g default-terminal "screen-256color"                   # enable true color
set -g prefix C-s                                           # change prefix key
set -g mouse on                                             # enable mouse
set -g history-limit 50000                                  # scrollback buffer size
set -g set-clipboard on                                     # use system clipboard
set -g base-index 1                                         # index windows at 1
set -g renumber-windows on                                  # renumber windows
set -g detach-on-destroy off                                # don't exit tmux on kill-session
setw -g mode-keys vi                                        # enable copy mode

## Reload Config
bind r source-file ~/.config/tmux/tmux.conf
display-message "RELOADED!"

## Bindings
bind-key C-s send-prefix
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection
bind s list-windows
bind c copy-mode
bind p paste-buffer
bind | split-window -h
bind - split-window -v
bind ! kill-window
bind x kill-pane
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r m resize-pane -Z

## Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/yank'
set -g @plugin 'tmux-plugins/tmux-ressurect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

## Ressurect & Continuum Config
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'

## Dracula Theme Config
set -g status-position top
set -g @dracula-show-flags true
set -g @dracula-border-contrast true
set -g @dracula-show-left-icon ""
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false
set -g @dracula-plugins "time weather battery"
set -g @dracula-battery-label " "
set -g @dracula-time-colors "dark_purple white"
set -g @dracula-weather-colors "cyan dark_gray"
set -g @dracula-battery-colors "light_purple dark_gray"

# Initialize TMUX plugin manager (keep this line at the very bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
