export TERM="wezterm"
export GLOBAL_THEME="everforest"
export XDG_CONFIG_HOME="$HOME/.config"
export WEZTERM_CONFIG_FILE="$XDG_CONFIG_HOME/wezterm/wezterm.lua"
export TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
